### ISSUE TITLE
import issue: from ssms.basic_simulators.boundary_functions import *

### ISSUE THREAD

**Issue by panwanke** [AlexanderFengler/ssm-simulators#7]
File [d:\01Redirect\04miniconda3\envs\py39hddm\lib\site-packages\ssms\basic_simulators\simulator.py:7](file:///D:/01Redirect/04miniconda3/envs/py39hddm/lib/site-packages/ssms/basic_simulators/simulator.py:7)
      5 import sys
      6 from copy import deepcopy
----> 7 import cssm
     10 # Basic simulators and basic preprocessing
...
     15 ):  # ['v', 'a', 'w', 't', 'angle']

File src\cssm.pyx:1, in init cssm()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by Asynchro-Epool** [comment]
This issue occur when the version of numpy is 1.21.0. 

When the numpy upgrade to 1.24.3, ssms could be loaded successfully, but when lodaing the hddm I get another problem:
     17 from numpy import array, ndarray, reshape, Inf, asarray, dot, sum, float, isnan, size, NaN, asanyarray
     18 import numpy as np
     19 from numpy import shape, size, ravel, zeros, ones, reshape, newaxis, broadcast, ndim, expand_dims

ImportError: cannot import name 'float' from 'numpy'

**Comment by Asynchro-Epool** [comment]
I figure out this issue with replacement from the `float` to `float64` in `PyMCObjects.py`
